### ISSUE TITLE
Module Dependencies

### ISSUE THREAD

**Issue by formburg** [derhaeuptling/contao-lazy-images#1]
Sobald in den Einstellungen Inaktive Erweiterungen wie Kalender oder Events angeklickt sind, kommt folgende Fehlermeldung und nichts geht mehr:

The module dependencies could not be resolved.
Array
(
    [lazy-images] => Array
        (
            [0] => core
            [1] => news
            [2] => calendar
            [3] => faq
        )
)

Für alle, die gleiches problem hatten, einfach ein leeres .skip File in den Modulordner legen und die Inaktiven Erweiterungen wieder aktivieren.

**Comment by Metis77** [comment]
In 426814d those dependencies have been removed.
