### ISSUE TITLE
Problems with "webp" in Contao 4.8

### ISSUE THREAD

**Issue by heimseiten** [derhaeuptling/contao-lazy-images#10]
First thank you very much for this great plugin!

If "Convert image formats" is enabled in Contao 4.8, the images will not be displayed in Safari. If the image setting "Disable Lazy Images" is enabled, the images will be displayed in Safari.

**Comment by Metis77** [comment]
this plugin is not tested or prepared for contao 4.8.
since contao 4.8 a lot changed we probably would need several adjustments.
Right now the is no current project that offers some budget to investigate this.

**Comment by heimseiten** [comment]
Ok. Thanks for the quick feedback.
