### ISSUE TITLE
Problems with "contao-bootstrap" img-fluid class

### ISSUE THREAD

**Issue by cmichael-de** [derhaeuptling/contao-lazy-images#11]
Maybe the following problem is helpful to avoid conflicts between other contao extensions:

I install "contao-lazy-images" and "contao-bootstrap". I enter "img-fluid" into the backends expert>class>field of an ce_image element. The extension "contao-bootstrap" usually takes the class "img-fluid" from the ce_image deeper into the DOM and moves it directly to the img class. But the "lazyloaded" class seems to be stronge ;-). The "img-fluid" doesn't occure, neither on the ce_image element nor on the img element.

I deinstall  "contao-lazy-images" and the  "img-fluid" is added as expected to the img class.

**Comment by Metis77** [comment]
the contao-lazy-images heavily overwrites default picture.html5.
If any other plugin does the same, there will be a conflict.

**Comment by cmichael-de** [comment]
Thank you @Metis77.
I suggest to add known conflicts to contao-lazy-images/composer.json.
Would be helpful for all contao-lazy-images useres (for you as well ;-).

https://github.com/contao-bootstrap/layout/issues/15

**Comment by dmolineus** [comment]
Instead of defining an conflict the issue schould be solved.

Contao bootstrap renders a `class` attribute using the `$this->attributes` of the template because the previous Contao core picture template didn't have the class attribute computed in the template.

**Comment by Metis77** [comment]
Would you like to offer a pull request?

**Comment by dmolineus** [comment]
Gonna be fixed on contao-bootstrap side, so you shouldn't have to do anything
