### ISSUE TITLE
Lazy Images deaktivieren beim Element ce_image (Bild-Element)

### ISSUE THREAD

**Issue by green-pixelbox** [derhaeuptling/contao-lazy-images#4]
Ein wirklich super Modul! Danke dafür! Es wäre noch toll, wenn man bei den Bild-Elementen von Contao lazy-images auch deaktivieren könnte, so wie dass auch bei den Text-Elementen unter den Bildeinstellungen machen kann.

**Comment by Metis77** [comment]
Contao 4 nehme ich an?
Wir schauen uns das an.

**Comment by green-pixelbox** [comment]
Ja, bei Contao 4.4 und 4.5 :)

**Comment by Metis77** [comment]
fixed in 744d3e0.
tag 3.0.2 released.
