### ISSUE TITLE
Anderes Bild für Mobilgeräte funktioniert nicht

### ISSUE THREAD

**Issue by bschi** [derhaeuptling/contao-lazy-images#5]
Hallo,

diese Anfrage bezieht sich auf https://github.com/derhaeuptling/contao-mobilecontent, hat allerdings evtl. etwas hiermit zu tun.

Ich habe die Herausforderung, dass diese Option mit den folgenden Parametern (siehe Anhang) nicht funktioniert. Standardmäßig wird ein Hochkant-Bild geladen, das zeigt es allerdings auch auf meinem Smartphone an. Dort müsste es eigentlich Querformat haben. Ich kann auch das Bild für mobile Endgeräte nicht ausblenden, diese Option funktioniert bei mir auch leider nicht.

![2018-04-19 10_37_57-](https://user-images.githubusercontent.com/7568056/38980839-2cfe0962-43be-11e8-8e31-bb3dee890e79.png)

Zusätzlich habe ich u.a. folgende Erweiterung installiert, vielleicht ist das auch nicht miteinander kompatibel?
- https://github.com/derhaeuptling/contao-lazy-images
- https://github.com/derhaeuptling/contao-mobilecontent

Ich nutze Contao 4.4.18 und jeweils die neuesten Versionen der Plugins.

Danke für die Hilfe und viele Grüße!

**Comment by Metis77** [comment]
Ich habe eben getestet, und glaube, dass es an contao-mobilecontent liegt.
Wir schauen uns das bei Gelegenheit an.

**Comment by Metis77** [comment]
@bschi kannst du mal die neue Version von MobileContent testen: 2.2.1
Damit kann ich hier keine Fehler mehr reproduzieren.

**Comment by bschi** [comment]
@Metis77 Danke für den schnellen Fix. Er funktioniert bei mir leider nicht.

Als Testgeräte nutze ich iPhone 7 und iPhone X. Ich habe mal etwas getestet und ich glaube es liegt an der Erkennung des Mobilgerätes. Ich kann bspw. auch keine Contentelemente für diese Geräte ausblenden bzw. werden diese nicht ausgeblendet. Wenn ich jedoch das Contentelement für Desktop ausblende, dann wird es auch für die mobilen Endgeräte ausgeblendet.

**Comment by Metis77** [comment]
hm, komisch.
Wir konnten wir hier keine Fehler mehr reproduzieren. 

Somit bleibt leider nur noch der individuelle Support.
Denn könnt ihr gerne per E-Mail beauftragen – dann schauen wir uns das konkret auf eurem System genau an.
