### ISSUE TITLE
Overwrite "CSS classes" in "Image size settings"

### ISSUE THREAD

**Issue by Y-Nell** [derhaeuptling/contao-lazy-images#6]
If this extension is active it overwrites the "CSS classes" in "Image size settings".

Found in: Contao 4.4.30, contao-lazy-images 3.0.3

**Comment by Metis77** [comment]
@sebastijanr Hey Sebastian, would you like to check this?

**Comment by Metis77** [comment]
Solved in version 3.0.4.
