### ISSUE TITLE
Deaktivierung bei eigenen Elementen?

### ISSUE THREAD

**Issue by ngdot** [derhaeuptling/contao-lazy-images#7]
Hi, wenn ich eigene Content-Elemente über die Erweiterung von RockSolid baue, werden alle Bilder automatisch mit eurer Erweiterung "lazygeloaded", wie kann ich dafür sorgen das meine eigenen Elemente davon ausgenommen werden? Das Standard "picture_default" Template ist doch nicht verändert, oder?

**Comment by ngdot** [comment]
Den einzigen Weg den ich bis jetzt gefunden habe, ist es ein Duplikat von "picture_default" in den eigenen Elemente zu benutzen. Ich habe ebenfalls versucht eine Checkbox mit dem Namen "lazyDisable" in meinem eigenen Element anzulegen um so die Funktion der normalen Content-Elemente anzunehmen, leider ohne Erfolg.

**Comment by Metis77** [comment]
> Das Standard "picture_default" Template ist doch nicht verändert, oder?

Doch genau das ist der Fall.
Wenn du aber dein eigenes Template verwendest, dann gilt wiederum dieses – aber auch für die anderen LazyImages.

**Comment by ngdot** [comment]
Alles klar, danke!
