### ISSUE TITLE
Outdates lazysizes script

### ISSUE THREAD

**Issue by dmolineus** [derhaeuptling/contao-lazy-images#8]
The shipped lazysizes script has the version 4.0.2. There is version 4.1.8 availalbe - this provides some fixes for issues using the IE. Would be great if the lib could be updated.

**Comment by Metis77** [comment]
There is also a Version 5 released just now.
What should be used?

**Comment by Metis77** [comment]
The next time this plugins receives some love, we will try to offer the more modern v5 of lazysizes with the intersection observer.
We would also like to offer a fallback to the old scroll event listener.
